apiVersion: v1
kind: Service
metadata:
  name: svc-safc
spec:
  type: NodePort
  selector:
    app: tickets
    club: safc
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 8080
      nodePort: 31111
