# Empty file. Use this to define the new StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1 
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain

