apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      track: canary
  template:
    metadata:
      labels:
        track: canary
        app: customer-app
    spec:
      containers:
      - name: canary
        image: ckad:canary
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" # 128 MB
            cpu: "200m" # 200 millicpu (.2 cpu or 20% of the cpu)
      # - name: temp-pod
      #   image: alpine:3.17
      #   imagePullPolicy: IfNotPresent
      #   command: ["/bin/sh"]
      #   args: ["-c", "while true; do echo hello; sleep 10;done"]
      #   resources:
      #     limits:
      #       memory: "128Mi" # 128 MB
      #       cpu: "200m" # 200 mil
